server.port=5454

spring.datasource.url=jdbc:mysql://localhost:3307/anh_food_yt
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

stripe.api.key=sk_test_51Tbe080GM3xD5WWyOmBG38ynynaXFMJrgqTcy3GYrZAgDQbMSYkg0BcOJZjXG9FapdTDx6bdJwsmI8nmdonlHF6s00WQFudlnB