export const CREATE_REVIEW_REQUEST = 'CREATE_REVIEW_REQUEST';
export const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS';
export const CREATE_REVIEW_FAILURE = 'CREATE_REVIEW_FAILURE';

export const GET_RESTAURANT_REVIEWS_REQUEST = 'GET_RESTAURANT_REVIEWS_REQUEST';
export const GET_RESTAURANT_REVIEWS_SUCCESS = 'GET_RESTAURANT_REVIEWS_SUCCESS';
export const GET_RESTAURANT_REVIEWS_FAILURE = 'GET_RESTAURANT_REVIEWS_FAILURE';

export const GET_FOOD_REVIEWS_REQUEST = 'GET_FOOD_REVIEWS_REQUEST';
export const GET_FOOD_REVIEWS_SUCCESS = 'GET_FOOD_REVIEWS_SUCCESS';
export const GET_FOOD_REVIEWS_FAILURE = 'GET_FOOD_REVIEWS_FAILURE';

export const UPDATE_REVIEW_REQUEST = 'UPDATE_REVIEW_REQUEST';
export const UPDATE_REVIEW_SUCCESS = 'UPDATE_REVIEW_SUCCESS';
export const UPDATE_REVIEW_FAILURE = 'UPDATE_REVIEW_FAILURE';

export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST';
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';
export const DELETE_REVIEW_FAILURE = 'DELETE_REVIEW_FAILURE';

