export const GET_MENU_ITEMS_BY_RESTAURANT_ID_REQUEST = "GET_MENU_ITEMS_BY_RESTAURANT_ID_REQUEST";
export const GET_MENU_ITEMS_BY_RESTAURANT_ID_SUCCESS = "GET_MENU_ITEMS_BY_RESTAURANT_ID_SUCCESS";
export const GET_MENU_ITEMS_BY_RESTAURANT_ID_FAILURE = "GET_MENU_ITEMS_BY_RESTAURANT_ID_FAILURE";

export const SEARCH_MENU_ITEM_REQUEST = "SEARCH_MENU_ITEM_REQUEST";
export const SEARCH_MENU_ITEM_SUCCESS = "SEARCH_MENU_ITEM_SUCCESS";
export const SEARCH_MENU_ITEM_FAILURE = "SEARCH_MENU_ITEM_FAILURE";